apiVersion: apps/v1
kind: Deployment
metadata:
  name: express
  namespace: oleeng
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:  
      containers:
      - name: express
        image: docker.io/oleeng/hello-express
        ports:
        - containerPort: 80
          protocol: TCP
        env:
        - name: PORT
          value: '8080'
